export default {
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_ERROR: 'SIGNIN_ERROR',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
  SIGNUP_REQUEST: 'REGISTER_REQUEST',
  SIGNIN_REQUEST: 'LOGIN_REQUEST',
  SET_TOKEN: 'SET_TOKEN',
  LOGOUT: 'LOGOUT',
};
