export default {
  GET_EXPENSES_REQUEST: 'GET_EXPENSES_REQUEST',
  ADD_EXPENSE_REQUEST: 'ADD_EXPENSE_REQUEST',
  EXPENSES_LOADING: 'EXPENSES_LOADING',
  ADD_EXPENSE_SUCCESSFULL: 'ADD_EXPENSE_SUCCESSFULL',
  GET_EXPENSES_SUCCESSFULL: 'GET_EXPENSES_SUCCESSFULL',
  SET_ERROR: 'SET_ERROR',
};
