export default {
  GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
  ADD_CATEGORY_REQUEST: 'ADD_CATEGORY_REQUEST',
  CATEGORIES_LOADING: 'CATEGORIES_LOADING',
  ADD_CATEGORY_SUCCESSFULL: 'ADD_CATEGORY_SUCCESSFULL',
  GET_CATEGORIES_SUCCESSFULL: 'GET_CATEGORIES_SUCCESSFULL',
  SET_ERROR: 'SET_ERROR',
};
